defmodule IntellectualClub.Repo.Migrations.AddLinkedForkAnchors do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:chats) do
      add :fork_task, :text

      add :fork_source_step_id,
          references(:chat_message_steps,
            column: :id,
            name: "chats_fork_source_step_id_fkey",
            type: :bigint,
            prefix: "public"
          )
    end

    create index(:chats, [:fork_source_step_id], name: "chats_fork_source_step_id_index")
  end

  def down do
    drop constraint(:chats, "chats_fork_source_step_id_fkey")

    drop_if_exists index(:chats, [:fork_source_step_id], name: "chats_fork_source_step_id_index")

    alter table(:chats) do
      remove :fork_source_step_id
      remove :fork_task
    end
  end
end
