defmodule IntellectualClub.Repo.Migrations.DetachDeletedLegacyChatParents do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint(:chats, "chats_parent_message_id_fkey")

    drop constraint(:chats, "chats_parent_chat_id_fkey")

    alter table(:chats) do
      modify :parent_chat_id,
             references(:chats,
               column: :id,
               name: "chats_parent_chat_id_fkey",
               type: :bigint,
               prefix: "public",
               on_delete: :nilify_all
             )

      modify :parent_message_id,
             references(:chat_messages,
               column: :id,
               name: "chats_parent_message_id_fkey",
               type: :bigint,
               prefix: "public",
               on_delete: :nilify_all
             )
    end
  end

  def down do
    drop constraint(:chats, "chats_parent_chat_id_fkey")

    drop constraint(:chats, "chats_parent_message_id_fkey")

    alter table(:chats) do
      modify :parent_message_id,
             references(:chat_messages,
               column: :id,
               name: "chats_parent_message_id_fkey",
               type: :bigint,
               prefix: "public"
             )

      modify :parent_chat_id,
             references(:chats,
               column: :id,
               name: "chats_parent_chat_id_fkey",
               type: :bigint,
               prefix: "public"
             )
    end
  end
end
