defmodule IntellectualClub.Repo.Migrations.AddWebPushDeliveryClaim do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:web_push_generation_events) do
      add :delivery_token, :uuid
      add :delivery_expires_at, :utc_datetime_usec
    end
  end

  def down do
    alter table(:web_push_generation_events) do
      remove :delivery_expires_at
      remove :delivery_token
    end
  end
end
