defmodule IntellectualClub.Repo.Migrations.ToolFunctionDiscoveryAvailability do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:tool_functions) do
      add :discovery_available, :boolean, null: false, default: true
    end
  end

  def down do
    alter table(:tool_functions) do
      remove :discovery_available
    end
  end
end
