defmodule IntellectualClub.Repo.Migrations.AddForkUnavailableFunctions do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:chats) do
      add :fork_unavailable_functions, {:array, :text}
    end
  end

  def down do
    alter table(:chats) do
      remove :fork_unavailable_functions
    end
  end
end
