defmodule IntellectualClub.Repo.Migrations.ManagedSecretOwnership do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    execute("""
    DELETE FROM managed_secrets AS secret
    WHERE NOT EXISTS (
      SELECT 1 FROM knowledge_block_secrets AS binding WHERE binding.secret_id = secret.id
    )
    AND NOT EXISTS (
      SELECT 1 FROM tool_instance_secrets AS binding WHERE binding.secret_id = secret.id
    )
    """)

    create unique_index(:tool_instance_secrets, [:secret_id],
             name: "tool_instance_secrets_unique_secret_index"
           )

    create unique_index(:knowledge_block_secrets, [:secret_id],
             name: "knowledge_block_secrets_unique_secret_index"
           )
  end

  def down do
    drop_if_exists unique_index(:knowledge_block_secrets, [:secret_id],
                     name: "knowledge_block_secrets_unique_secret_index"
                   )

    drop_if_exists unique_index(:tool_instance_secrets, [:secret_id],
                     name: "tool_instance_secrets_unique_secret_index"
                   )
  end
end
