defmodule IntellectualClub.Repo.Migrations.BackgroundTaskActiveIndexes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create index(:background_tasks, [:tool_instance_id, :adapter, :status, :inserted_at],
             name: "background_tasks_active_tool_adapter_index",
             where: "status IN ('queued', 'running')"
           )

    create index(:background_tasks, [:status, :inserted_at],
             name: "background_tasks_active_status_inserted_index",
             where: "status IN ('queued', 'running')"
           )
  end

  def down do
    drop_if_exists index(:background_tasks, [:status, :inserted_at],
                     name: "background_tasks_active_status_inserted_index"
                   )

    drop_if_exists index(:background_tasks, [:tool_instance_id, :adapter, :status, :inserted_at],
                     name: "background_tasks_active_tool_adapter_index"
                   )
  end
end
