defmodule IntellectualClub.Repo.Migrations.LowerLlmConfigurationTimeoutDefault do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:llm_configurations) do
      modify :timeout_seconds, :bigint, default: 120
    end
  end

  def down do
    alter table(:llm_configurations) do
      modify :timeout_seconds, :bigint, default: 300
    end
  end
end
