defmodule IntellectualClub.Repo.Migrations.AddSupportsSteering do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:llm_configurations) do
      add :supports_steering, :boolean, null: false, default: true
    end
  end

  def down do
    alter table(:llm_configurations) do
      remove :supports_steering
    end
  end
end
