defmodule IntellectualClub.Repo.Migrations.AddLastTokenAtToChatMessageSteps do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:chat_message_steps) do
      add :last_token_at, :utc_datetime_usec
    end
  end

  def down do
    alter table(:chat_message_steps) do
      remove :last_token_at
    end
  end
end
