defmodule IntellectualClub.Repo.Migrations.AddMessagePollRevisions do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:chat_message_poll_revisions, primary_key: false) do
      add :chat_message_id,
          references(:chat_messages,
            column: :id,
            name: "chat_message_poll_revisions_chat_message_id_fkey",
            type: :bigint,
            prefix: "public",
            on_delete: :delete_all
          ), primary_key: true, null: false

      add :revision, :bigint, null: false, default: 0
    end

    execute("""
    CREATE OR REPLACE FUNCTION advance_message_trace_revision()
    RETURNS trigger AS $$
    DECLARE message_id bigint;
    BEGIN
      IF TG_TABLE_NAME = 'chat_message_steps' THEN
        message_id := CASE WHEN TG_OP = 'DELETE' THEN OLD.chat_message_id ELSE NEW.chat_message_id END;
      ELSIF TG_TABLE_NAME = 'chat_message_items' THEN
        SELECT chat_message_id INTO message_id FROM chat_message_steps
          WHERE id = CASE WHEN TG_OP = 'DELETE' THEN OLD.chat_message_step_id ELSE NEW.chat_message_step_id END;
      ELSE
        SELECT s.chat_message_id INTO message_id FROM chat_message_items i
          JOIN chat_message_steps s ON s.id = i.chat_message_step_id
          WHERE i.id = CASE WHEN TG_OP = 'DELETE' THEN OLD.chat_message_item_id ELSE NEW.chat_message_item_id END;
      END IF;
      INSERT INTO chat_message_poll_revisions (chat_message_id, revision)
        SELECT id, 1 FROM chat_messages WHERE id = message_id
        ON CONFLICT (chat_message_id) DO UPDATE
          SET revision = chat_message_poll_revisions.revision + 1;
      RETURN NULL;
    END;
    $$ LANGUAGE plpgsql;
    """)

    execute("""
    CREATE TRIGGER advance_step_trace_revision AFTER INSERT OR UPDATE OR DELETE ON chat_message_steps FOR EACH ROW EXECUTE FUNCTION advance_message_trace_revision()
    """)

    execute("""
    CREATE TRIGGER advance_item_trace_revision AFTER INSERT OR UPDATE OR DELETE ON chat_message_items FOR EACH ROW EXECUTE FUNCTION advance_message_trace_revision()
    """)

    execute("""
    CREATE TRIGGER advance_content_trace_revision AFTER INSERT OR UPDATE OR DELETE ON chat_message_contents FOR EACH ROW EXECUTE FUNCTION advance_message_trace_revision()
    """)
  end

  def down do
    execute("""
    DROP TRIGGER IF EXISTS advance_content_trace_revision ON chat_message_contents
    """)

    execute("""
    DROP TRIGGER IF EXISTS advance_item_trace_revision ON chat_message_items
    """)

    execute("""
    DROP TRIGGER IF EXISTS advance_step_trace_revision ON chat_message_steps
    """)

    execute("""
    DROP FUNCTION IF EXISTS advance_message_trace_revision()
    """)

    drop constraint(
           :chat_message_poll_revisions,
           "chat_message_poll_revisions_chat_message_id_fkey"
         )

    drop table(:chat_message_poll_revisions)
  end
end
