defmodule IntellectualClub.Repo.Migrations.AddWebPushSubscriptionDeviceId do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:web_push_subscriptions) do
      add :device_id, :text
    end

    create index(:web_push_subscriptions, [:owner_id, :device_id],
             name: "web_push_subscriptions_owner_id_device_id_index",
             where: "device_id IS NOT NULL"
           )
  end

  def down do
    drop_if_exists index(:web_push_subscriptions, [:owner_id, :device_id],
                     name: "web_push_subscriptions_owner_id_device_id_index"
                   )

    alter table(:web_push_subscriptions) do
      remove :device_id
    end
  end
end
