defmodule IntellectualClub.Repo.Migrations.Init do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    execute("""
    CREATE OR REPLACE FUNCTION ash_elixir_or(left BOOLEAN, in right ANYCOMPATIBLE, out f1 ANYCOMPATIBLE)
    AS $$ SELECT COALESCE(NULLIF($1, FALSE), $2) $$
    LANGUAGE SQL
    SET search_path = ''
    IMMUTABLE;
    """)

    execute("""
    CREATE OR REPLACE FUNCTION ash_elixir_or(left ANYCOMPATIBLE, in right ANYCOMPATIBLE, out f1 ANYCOMPATIBLE)
    AS $$ SELECT COALESCE($1, $2) $$
    LANGUAGE SQL
    SET search_path = ''
    IMMUTABLE;
    """)

    execute("""
    CREATE OR REPLACE FUNCTION ash_elixir_and(left BOOLEAN, in right ANYCOMPATIBLE, out f1 ANYCOMPATIBLE) AS $$
      SELECT CASE
        WHEN $1 IS TRUE THEN $2
        ELSE $1
      END $$
    LANGUAGE SQL
    SET search_path = ''
    IMMUTABLE;
    """)

    execute("""
    CREATE OR REPLACE FUNCTION ash_elixir_and(left ANYCOMPATIBLE, in right ANYCOMPATIBLE, out f1 ANYCOMPATIBLE) AS $$
      SELECT CASE
        WHEN $1 IS NOT NULL THEN $2
        ELSE $1
      END $$
    LANGUAGE SQL
    SET search_path = ''
    IMMUTABLE;
    """)

    execute("""
    CREATE OR REPLACE FUNCTION ash_trim_whitespace(arr text[])
    RETURNS text[] AS $$
    DECLARE
        start_index INT = 1;
        end_index INT = array_length(arr, 1);
    BEGIN
        WHILE start_index <= end_index AND arr[start_index] = '' LOOP
            start_index := start_index + 1;
        END LOOP;

        WHILE end_index >= start_index AND arr[end_index] = '' LOOP
            end_index := end_index - 1;
        END LOOP;

        IF start_index > end_index THEN
            RETURN ARRAY[]::text[];
        ELSE
            RETURN arr[start_index : end_index];
        END IF;
    END; $$
    LANGUAGE plpgsql
    SET search_path = ''
    IMMUTABLE;
    """)

    execute("""
    CREATE OR REPLACE FUNCTION ash_raise_error(json_data jsonb)
    RETURNS BOOLEAN AS $$
    BEGIN
        -- Raise an error with the provided JSON data.
        -- The JSON object is converted to text for inclusion in the error message.
        RAISE EXCEPTION 'ash_error: %', json_data::text;
        RETURN NULL;
    END;
    $$ LANGUAGE plpgsql
    STABLE
    SET search_path = '';
    """)

    execute("""
    CREATE OR REPLACE FUNCTION ash_raise_error(json_data jsonb, type_signal ANYCOMPATIBLE)
    RETURNS ANYCOMPATIBLE AS $$
    BEGIN
        -- Raise an error with the provided JSON data.
        -- The JSON object is converted to text for inclusion in the error message.
        RAISE EXCEPTION 'ash_error: %', json_data::text;
        RETURN NULL;
    END;
    $$ LANGUAGE plpgsql
    STABLE
    SET search_path = '';
    """)

    execute("""
    CREATE OR REPLACE FUNCTION ash_required(value ANYCOMPATIBLE, payload jsonb)
    RETURNS ANYCOMPATIBLE AS $$
    BEGIN
      IF value IS NULL THEN
        RETURN ash_raise_error(payload, value);
      END IF;

      RETURN value;
    END;
    $$ LANGUAGE plpgsql
    STABLE
    SET search_path = '';
    """)

    execute("""
    CREATE OR REPLACE FUNCTION uuid_generate_v7()
    RETURNS UUID
    AS $$
    DECLARE
      timestamp    TIMESTAMPTZ;
      microseconds INT;
    BEGIN
      timestamp    = clock_timestamp();
      microseconds = (cast(extract(microseconds FROM timestamp)::INT - (floor(extract(milliseconds FROM timestamp))::INT * 1000) AS DOUBLE PRECISION) * 4.096)::INT;

      RETURN encode(
        set_byte(
          set_byte(
            overlay(uuid_send(gen_random_uuid()) placing substring(int8send(floor(extract(epoch FROM timestamp) * 1000)::BIGINT) FROM 3) FROM 1 FOR 6
          ),
          6, (b'0111' || (microseconds >> 8)::bit(4))::bit(8)::int
        ),
        7, microseconds::bit(8)::int
      ),
      'hex')::UUID;
    END
    $$
    LANGUAGE PLPGSQL
    SET search_path = ''
    VOLATILE;
    """)

    execute("CREATE EXTENSION IF NOT EXISTS \"pg_trgm\"")

    create table(:user_group_memberships, primary_key: false) do
      add :id, :bigserial, null: false, primary_key: true

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id, :bigint, null: false
      add :user_group_id, :bigint, null: false
    end

    create index(:user_group_memberships, [:user_group_id],
             name: "user_group_memberships_user_group_id_index"
           )

    create index(:user_group_memberships, [:user_id],
             name: "user_group_memberships_user_id_index"
           )

    create unique_index(:user_group_memberships, [:user_id, :user_group_id],
             name: "user_group_memberships_unique_pair_index"
           )

    create table(:chat_message_steps, primary_key: false) do
      add :id, :bigserial, null: false, primary_key: true
      add :sequence, :bigint, null: false
      add :status, :text, null: false, default: "done"
      add :raw_request, :map, null: false, default: %{}
      add :raw_response, :map
      add :response_final, :boolean, null: false, default: false
      add :input_tokens, :bigint
      add :output_tokens, :bigint
      add :cached_input_tokens, :bigint
      add :reasoning_tokens, :bigint
      add :cost, :float
      add :first_token_at, :utc_datetime_usec
      add :finished_at, :utc_datetime_usec

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :owner_id, :bigint, null: false
      add :chat_message_id, :bigint, null: false
    end

    create unique_index(:chat_message_steps, [:chat_message_id, :sequence],
             name: "chat_message_steps_unique_chat_message_sequence_index"
           )

    create table(:llm_configuration_knowledge_blocks, primary_key: false) do
      add :id, :bigserial, null: false, primary_key: true
      add :selection, :text, null: false, default: "bottom"
      add :enabled, :boolean, null: false, default: true
      add :sequence, :bigint, null: false, default: 0

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :owner_id, :bigint, null: false
      add :llm_configuration_id, :bigint, null: false
      add :knowledge_block_id, :bigint, null: false
    end

    create index(:llm_configuration_knowledge_blocks, [:llm_configuration_id, :enabled],
             name: "llm_configuration_knowledge_blocks_config_enabled_index"
           )

    create unique_index(
             :llm_configuration_knowledge_blocks,
             [:llm_configuration_id, :knowledge_block_id],
             name: "llm_configuration_knowledge_blocks_unique_pair_index"
           )

    create table(:llm_configuration_tags, primary_key: false) do
      add :id, :bigserial, null: false, primary_key: true
      add :name, :text, null: false

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :owner_id, :bigint, null: false
    end

    create unique_index(:llm_configuration_tags, [:owner_id, :name],
             name: "llm_configuration_tags_unique_name_index"
           )

    create table(:bot_compatible_configuration_tags, primary_key: false) do
      add :id, :bigserial, null: false, primary_key: true

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :owner_id, :bigint, null: false
      add :bot_id, :bigint, null: false
      add :llm_configuration_tag_id, :bigint, null: false
    end

    create index(:bot_compatible_configuration_tags, [:llm_configuration_tag_id],
             name: "bot_compatible_configuration_tags_llm_configuration_tag_id_index"
           )

    create index(:bot_compatible_configuration_tags, [:bot_id],
             name: "bot_compatible_configuration_tags_bot_id_index"
           )

    create index(:bot_compatible_configuration_tags, [:owner_id],
             name: "bot_compatible_configuration_tags_owner_id_index"
           )

    create unique_index(:bot_compatible_configuration_tags, [:bot_id, :llm_configuration_tag_id],
             name: "bot_compatible_configuration_tags_unique_pair_index"
           )

    create table(:user_groups, primary_key: false) do
      add :id, :bigserial, null: false, primary_key: true
      add :name, :text, null: false

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:user_groups, [:name], name: "user_groups_unique_name_index")

    create table(:chat_upload_sessions, primary_key: false) do
      add :id, :bigserial, null: false, primary_key: true
      add :external_id, :uuid, null: false, default: fragment("gen_random_uuid()")
      add :filename, :text, null: false
      add :mime_type, :text, null: false
      add :size_bytes, :bigint, null: false
      add :uploaded_bytes, :bigint, null: false, default: 0
      add :chunk_size_bytes, :bigint, null: false
      add :status, :text, null: false, default: "uploading"
      add :expires_at, :utc_datetime_usec, null: false

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :owner_id, :bigint, null: false
      add :chat_id, :bigint, null: false
    end

    create index(:chat_upload_sessions, [:expires_at],
             name: "chat_upload_sessions_expires_at_index"
           )

    create index(:chat_upload_sessions, [:status], name: "chat_upload_sessions_status_index")

    create index(:chat_upload_sessions, [:owner_id], name: "chat_upload_sessions_owner_id_index")

    create index(:chat_upload_sessions, [:chat_id], name: "chat_upload_sessions_chat_id_index")

    create unique_index(:chat_upload_sessions, [:external_id],
             name: "chat_upload_sessions_unique_external_id_index"
           )

    create table(:chat_message_items, primary_key: false) do
      add :id, :bigserial, null: false, primary_key: true
      add :sequence, :bigint, null: false
      add :type, :text, null: false

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :owner_id, :bigint, null: false
      add :chat_message_step_id, :bigint, null: false
      add :tool_call_item_id, :bigint
    end

    create index(:chat_message_items, [:tool_call_item_id],
             name: "chat_message_items_tool_call_item_id_index"
           )

    create unique_index(:chat_message_items, [:chat_message_step_id, :sequence],
             name: "chat_message_items_unique_step_sequence_index"
           )

    create table(:outlet_pairing_requests, primary_key: false) do
      add :id, :bigserial, null: false, primary_key: true
      add :user_code, :text, null: false
      add :device_code_hash, :text, null: false
      add :runner_kind, :text, null: false, default: ""
      add :requested_name, :text, null: false, default: ""
      add :created_ip, :text
      add :created_user_agent, :text, null: false, default: ""
      add :metadata, :map, null: false, default: %{}
      add :status, :text, null: false, default: "pending"
      add :expires_at, :utc_datetime_usec, null: false
      add :approved_at, :utc_datetime_usec
      add :delivered_at, :utc_datetime_usec
      add :consumed_at, :utc_datetime_usec

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :approved_by_id, :bigint
      add :tool_instance_id, :bigint
    end

    create index(:outlet_pairing_requests, [:status, :expires_at, :created_at],
             name: "outlet_pairing_requests_status_expires_created_index"
           )

    create index(:outlet_pairing_requests, [:device_code_hash],
             name: "outlet_pairing_requests_device_code_hash_index"
           )

    create unique_index(:outlet_pairing_requests, [:user_code],
             name: "outlet_pairing_requests_unique_user_code_index"
           )

    create table(:chats, primary_key: false) do
      add :id, :bigserial, null: false, primary_key: true
      add :note, :text, default: ""
      add :parent_relation_kind, :text

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :owner_id, :bigint, null: false
      add :bot_id, :bigint
      add :llm_configuration_id, :bigint
      add :last_message_id, :bigint
      add :parent_chat_id, :bigint
      add :parent_message_id, :bigint
    end

    create index(:chats, [:parent_relation_kind], name: "chats_parent_relation_kind_index")

    create index(:chats, [:parent_message_id], name: "chats_parent_message_id_index")

    create index(:chats, [:parent_chat_id], name: "chats_parent_chat_id_index")

    create index(:chats, [:owner_id, :updated_at, :id], name: "chats_owner_updated_id_index")

    create table(:user_knowledge_blocks, primary_key: false) do
      add :id, :bigserial, null: false, primary_key: true
      add :enabled, :boolean, null: false, default: true
      add :sequence, :bigint, null: false, default: 0

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :owner_id, :bigint, null: false
      add :knowledge_block_id, :bigint, null: false
    end

    create index(:user_knowledge_blocks, [:owner_id, :enabled],
             name: "user_knowledge_blocks_owner_enabled_index"
           )

    create index(:user_knowledge_blocks, [:owner_id],
             name: "user_knowledge_blocks_owner_id_index"
           )

    create unique_index(:user_knowledge_blocks, [:owner_id, :knowledge_block_id],
             name: "user_knowledge_blocks_unique_pair_index"
           )

    create table(:bot_tool_bindings, primary_key: false) do
      add :id, :bigserial, null: false, primary_key: true
      add :sharing_mode, :text, null: false, default: "shared"
      add :enabled, :boolean, null: false, default: true
      add :sequence, :bigint, null: false, default: 0

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :owner_id, :bigint, null: false
      add :bot_id, :bigint, null: false
      add :tool_instance_id, :bigint, null: false
    end

    create index(:bot_tool_bindings, [:owner_id], name: "bot_tool_bindings_owner_id_index")

    create unique_index(:bot_tool_bindings, [:bot_id, :tool_instance_id],
             name: "bot_tool_bindings_unique_bot_tool_instance_index"
           )

    create table(:chat_tool_bindings, primary_key: false) do
      add :id, :bigserial, null: false, primary_key: true
      add :enabled, :boolean, null: false, default: true
      add :sequence, :bigint, null: false, default: 0

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :owner_id, :bigint, null: false
      add :chat_id, :bigint, null: false
      add :tool_instance_id, :bigint, null: false
    end

    create index(:chat_tool_bindings, [:chat_id, :enabled],
             name: "chat_tool_bindings_chat_enabled_index"
           )

    create index(:chat_tool_bindings, [:owner_id], name: "chat_tool_bindings_owner_id_index")

    create unique_index(:chat_tool_bindings, [:chat_id, :tool_instance_id],
             name: "chat_tool_bindings_unique_chat_tool_instance_index"
           )

    create table(:bot_user_tool_bindings, primary_key: false) do
      add :id, :bigserial, null: false, primary_key: true
      add :enabled, :boolean, null: false, default: true
      add :sequence, :bigint, null: false, default: 0

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :owner_id, :bigint, null: false
      add :bot_id, :bigint, null: false
      add :tool_instance_id, :bigint, null: false
    end

    create unique_index(:bot_user_tool_bindings, [:owner_id, :bot_id, :tool_instance_id],
             name: "bot_user_tool_bindings_unique_owner_bot_tool_instance_index"
           )

    create table(:bots, primary_key: false) do
      add :id, :bigserial, null: false, primary_key: true
      add :external_id, :uuid, null: false, default: fragment("gen_random_uuid()")
      add :name, :text, null: false
      add :first_messages, {:array, :text}, null: false, default: []
      add :max_tool_rounds, :bigint, null: false, default: 300
      add :context_soft_limit_percent, :bigint, null: false, default: 80
      add :max_file_size_bytes, :bigint, null: false, default: 524_288_000
      add :history_mode, :text, null: false, default: "chat"

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :owner_id, :bigint, null: false
      add :image_file_id, :bigint
      add :default_llm_configuration_id, :bigint
      add :handoff_message_block_id, :bigint
    end

    create index(:bots, [:handoff_message_block_id], name: "bots_handoff_message_block_id_index")

    create index(:bots, [:default_llm_configuration_id],
             name: "bots_default_llm_configuration_id_index"
           )

    create index(:bots, [:image_file_id], name: "bots_image_file_id_index")

    create unique_index(:bots, [:external_id], name: "bots_unique_external_id_index")

    create table(:bot_knowledge_blocks, primary_key: false) do
      add :id, :bigserial, null: false, primary_key: true
      add :enabled, :boolean, null: false, default: true
      add :sequence, :bigint, null: false, default: 0

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :owner_id, :bigint, null: false
      add :bot_id, :bigint, null: false
      add :knowledge_block_id, :bigint, null: false
    end

    create index(:bot_knowledge_blocks, [:bot_id, :enabled],
             name: "bot_knowledge_blocks_bot_enabled_index"
           )

    create unique_index(:bot_knowledge_blocks, [:bot_id, :knowledge_block_id],
             name: "bot_knowledge_blocks_unique_pair_index"
           )

    create table(:llm_configurations, primary_key: false) do
      add :id, :bigserial, null: false, primary_key: true
      add :external_id, :uuid, null: false, default: fragment("gen_random_uuid()")
      add :model_name, :text, null: false
      add :note, :text
      add :parameters, :map, null: false, default: %{}
      add :enabled, :boolean, null: false, default: true
      add :timeout_seconds, :bigint, null: false, default: 300
      add :context_length, :bigint
      add :supports_cache_control, :boolean, null: false, default: false
      add :supports_image_input, :boolean, null: false, default: false
      add :fix_role_alteration, :boolean, null: false, default: false

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :owner_id, :bigint, null: false
      add :provider_id, :bigint, null: false
    end

    create unique_index(:llm_configurations, [:external_id],
             name: "llm_configurations_unique_external_id_index"
           )

    create table(:web_push_subscriptions, primary_key: false) do
      add :id, :bigserial, null: false, primary_key: true
      add :endpoint, :text, null: false
      add :p256dh, :text, null: false
      add :auth, :text, null: false
      add :user_agent, :text
      add :key_revision, :bigint, null: false
      add :expiration_time, :bigint
      add :last_seen_at, :utc_datetime_usec, null: false

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :owner_id, :bigint, null: false
    end

    create index(:web_push_subscriptions, [:owner_id],
             name: "web_push_subscriptions_owner_id_index"
           )

    create unique_index(:web_push_subscriptions, [:endpoint],
             name: "web_push_subscriptions_unique_endpoint_index"
           )

    create table(:web_push_generation_events, primary_key: false) do
      add :id, :bigserial, null: false, primary_key: true
      add :status, :text, null: false
      add :suppressed, :boolean, null: false, default: false
      add :delivered_count, :bigint, null: false, default: 0

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :owner_id, :bigint, null: false
      add :chat_message_id, :bigint, null: false
    end

    create index(:web_push_generation_events, [:owner_id],
             name: "web_push_generation_events_owner_id_index"
           )

    create unique_index(:web_push_generation_events, [:chat_message_id, :status],
             name: "web_push_generation_events_unique_message_status_index"
           )

    create table(:files, primary_key: false) do
      add :id, :bigserial, null: false, primary_key: true
      add :external_id, :uuid, null: false, default: fragment("gen_random_uuid()")
      add :sha256, :text, null: false
      add :filename, :text, null: false
      add :size_bytes, :bigint, null: false
      add :mime_type, :text, null: false
      add :storage_backend, :text, null: false, default: "fs"

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create index(:files, [:sha256], name: "files_sha256_index")

    create unique_index(:files, [:external_id], name: "files_unique_external_id_index")

    create table(:tokens, primary_key: false) do
      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :extra_data, :map
      add :purpose, :text, null: false
      add :expires_at, :utc_datetime, null: false
      add :subject, :text, null: false
      add :jti, :text, null: false, primary_key: true
    end

    create table(:knowledge_block_tags, primary_key: false) do
      add :id, :bigserial, null: false, primary_key: true

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :owner_id, :bigint, null: false
      add :knowledge_block_id, :bigint, null: false
      add :knowledge_tag_id, :bigint, null: false
    end

    create unique_index(:knowledge_block_tags, [:knowledge_block_id, :knowledge_tag_id],
             name: "knowledge_block_tags_unique_pair_index"
           )

    create table(:knowledge_tags, primary_key: false) do
      add :id, :bigserial, null: false, primary_key: true
      add :name, :text, null: false
      add :full_name, :text, null: false, default: ""

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :owner_id, :bigint, null: false
      add :parent_id, :bigint
    end

    create unique_index(:knowledge_tags, [:owner_id, :full_name],
             name: "knowledge_tags_unique_full_name_index"
           )

    create table(:users, primary_key: false) do
      add :id, :bigserial, null: false, primary_key: true
    end

    alter table(:user_group_memberships) do
      modify :user_id,
             references(:users,
               column: :id,
               name: "user_group_memberships_user_id_fkey",
               type: :bigint,
               prefix: "public"
             )

      modify :user_group_id,
             references(:user_groups,
               column: :id,
               name: "user_group_memberships_user_group_id_fkey",
               type: :bigint,
               prefix: "public"
             )
    end

    alter table(:chat_message_steps) do
      modify :owner_id,
             references(:users,
               column: :id,
               name: "chat_message_steps_owner_id_fkey",
               type: :bigint,
               prefix: "public"
             )
    end

    alter table(:llm_configuration_knowledge_blocks) do
      modify :owner_id,
             references(:users,
               column: :id,
               name: "llm_configuration_knowledge_blocks_owner_id_fkey",
               type: :bigint,
               prefix: "public"
             )

      modify :llm_configuration_id,
             references(:llm_configurations,
               column: :id,
               name: "llm_configuration_knowledge_blocks_llm_configuration_id_fkey",
               type: :bigint,
               prefix: "public"
             )
    end

    alter table(:llm_configuration_tags) do
      modify :owner_id,
             references(:users,
               column: :id,
               name: "llm_configuration_tags_owner_id_fkey",
               type: :bigint,
               prefix: "public"
             )
    end

    alter table(:bot_compatible_configuration_tags) do
      modify :owner_id,
             references(:users,
               column: :id,
               name: "bot_compatible_configuration_tags_owner_id_fkey",
               type: :bigint,
               prefix: "public"
             )

      modify :bot_id,
             references(:bots,
               column: :id,
               name: "bot_compatible_configuration_tags_bot_id_fkey",
               type: :bigint,
               prefix: "public"
             )

      modify :llm_configuration_tag_id,
             references(:llm_configuration_tags,
               column: :id,
               name: "bot_compatible_configuration_tags_llm_configuration_tag_id_fkey",
               type: :bigint,
               prefix: "public"
             )
    end

    alter table(:chat_upload_sessions) do
      modify :owner_id,
             references(:users,
               column: :id,
               name: "chat_upload_sessions_owner_id_fkey",
               type: :bigint,
               prefix: "public"
             )

      modify :chat_id,
             references(:chats,
               column: :id,
               name: "chat_upload_sessions_chat_id_fkey",
               type: :bigint,
               prefix: "public"
             )
    end

    alter table(:chat_message_items) do
      modify :owner_id,
             references(:users,
               column: :id,
               name: "chat_message_items_owner_id_fkey",
               type: :bigint,
               prefix: "public"
             )

      modify :chat_message_step_id,
             references(:chat_message_steps,
               column: :id,
               name: "chat_message_items_chat_message_step_id_fkey",
               type: :bigint,
               prefix: "public"
             )

      modify :tool_call_item_id,
             references(:chat_message_items,
               column: :id,
               name: "chat_message_items_tool_call_item_id_fkey",
               type: :bigint,
               prefix: "public"
             )
    end

    alter table(:outlet_pairing_requests) do
      modify :approved_by_id,
             references(:users,
               column: :id,
               name: "outlet_pairing_requests_approved_by_id_fkey",
               type: :bigint,
               prefix: "public"
             )
    end

    alter table(:chats) do
      modify :owner_id,
             references(:users,
               column: :id,
               name: "chats_owner_id_fkey",
               type: :bigint,
               prefix: "public"
             )

      modify :bot_id,
             references(:bots,
               column: :id,
               name: "chats_bot_id_fkey",
               type: :bigint,
               prefix: "public"
             )

      modify :llm_configuration_id,
             references(:llm_configurations,
               column: :id,
               name: "chats_llm_configuration_id_fkey",
               type: :bigint,
               prefix: "public"
             )
    end

    alter table(:user_knowledge_blocks) do
      modify :owner_id,
             references(:users,
               column: :id,
               name: "user_knowledge_blocks_owner_id_fkey",
               type: :bigint,
               prefix: "public"
             )
    end

    alter table(:bot_tool_bindings) do
      modify :owner_id,
             references(:users,
               column: :id,
               name: "bot_tool_bindings_owner_id_fkey",
               type: :bigint,
               prefix: "public"
             )

      modify :bot_id,
             references(:bots,
               column: :id,
               name: "bot_tool_bindings_bot_id_fkey",
               type: :bigint,
               prefix: "public"
             )
    end

    alter table(:chat_tool_bindings) do
      modify :owner_id,
             references(:users,
               column: :id,
               name: "chat_tool_bindings_owner_id_fkey",
               type: :bigint,
               prefix: "public"
             )

      modify :chat_id,
             references(:chats,
               column: :id,
               name: "chat_tool_bindings_chat_id_fkey",
               type: :bigint,
               prefix: "public"
             )
    end

    alter table(:bot_user_tool_bindings) do
      modify :owner_id,
             references(:users,
               column: :id,
               name: "bot_user_tool_bindings_owner_id_fkey",
               type: :bigint,
               prefix: "public"
             )

      modify :bot_id,
             references(:bots,
               column: :id,
               name: "bot_user_tool_bindings_bot_id_fkey",
               type: :bigint,
               prefix: "public"
             )
    end

    alter table(:bots) do
      modify :owner_id,
             references(:users,
               column: :id,
               name: "bots_owner_id_fkey",
               type: :bigint,
               prefix: "public"
             )

      modify :image_file_id,
             references(:files,
               column: :id,
               name: "bots_image_file_id_fkey",
               type: :bigint,
               prefix: "public"
             )

      modify :default_llm_configuration_id,
             references(:llm_configurations,
               column: :id,
               name: "bots_default_llm_configuration_id_fkey",
               type: :bigint,
               prefix: "public"
             )
    end

    alter table(:bot_knowledge_blocks) do
      modify :owner_id,
             references(:users,
               column: :id,
               name: "bot_knowledge_blocks_owner_id_fkey",
               type: :bigint,
               prefix: "public"
             )

      modify :bot_id,
             references(:bots,
               column: :id,
               name: "bot_knowledge_blocks_bot_id_fkey",
               type: :bigint,
               prefix: "public"
             )
    end

    alter table(:llm_configurations) do
      modify :owner_id,
             references(:users,
               column: :id,
               name: "llm_configurations_owner_id_fkey",
               type: :bigint,
               prefix: "public"
             )
    end

    alter table(:web_push_subscriptions) do
      modify :owner_id,
             references(:users,
               column: :id,
               name: "web_push_subscriptions_owner_id_fkey",
               type: :bigint,
               prefix: "public"
             )
    end

    alter table(:web_push_generation_events) do
      modify :owner_id,
             references(:users,
               column: :id,
               name: "web_push_generation_events_owner_id_fkey",
               type: :bigint,
               prefix: "public"
             )
    end

    alter table(:knowledge_block_tags) do
      modify :owner_id,
             references(:users,
               column: :id,
               name: "knowledge_block_tags_owner_id_fkey",
               type: :bigint,
               prefix: "public"
             )
    end

    alter table(:knowledge_tags) do
      modify :owner_id,
             references(:users,
               column: :id,
               name: "knowledge_tags_owner_id_fkey",
               type: :bigint,
               prefix: "public"
             )

      modify :parent_id,
             references(:knowledge_tags,
               column: :id,
               name: "knowledge_tags_parent_id_fkey",
               type: :bigint,
               prefix: "public"
             )
    end

    alter table(:users) do
      add :username, :text, null: false
      add :hashed_password, :text, null: false
      add :is_admin, :boolean, null: false, default: false
      add :preferred_locale, :text
      add :preferred_theme, :text, null: false, default: "system"

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:users, [:username], name: "users_unique_username_index")

    create table(:tool_instances, primary_key: false) do
      add :id, :bigserial, null: false, primary_key: true
    end

    alter table(:outlet_pairing_requests) do
      modify :tool_instance_id,
             references(:tool_instances,
               column: :id,
               name: "outlet_pairing_requests_tool_instance_id_fkey",
               type: :bigint,
               prefix: "public"
             )
    end

    alter table(:bot_tool_bindings) do
      modify :tool_instance_id,
             references(:tool_instances,
               column: :id,
               name: "bot_tool_bindings_tool_instance_id_fkey",
               type: :bigint,
               prefix: "public"
             )
    end

    alter table(:chat_tool_bindings) do
      modify :tool_instance_id,
             references(:tool_instances,
               column: :id,
               name: "chat_tool_bindings_tool_instance_id_fkey",
               type: :bigint,
               prefix: "public"
             )
    end

    alter table(:bot_user_tool_bindings) do
      modify :tool_instance_id,
             references(:tool_instances,
               column: :id,
               name: "bot_user_tool_bindings_tool_instance_id_fkey",
               type: :bigint,
               prefix: "public"
             )
    end

    alter table(:tool_instances) do
      add :type, :text, null: false
      add :name, :text, null: false
      add :description, :text, null: false, default: ""
      add :alias, :text, null: false, default: ""
      add :config, :map, null: false, default: %{}
      add :secrets, :map, null: false, default: %{}
      add :max_output_tokens, :bigint, null: false, default: 20000
      add :rps_limit, :float
      add :last_discovered_at, :utc_datetime_usec
      add :last_discovery_error, :text, null: false, default: ""

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :owner_id,
          references(:users,
            column: :id,
            name: "tool_instances_owner_id_fkey",
            type: :bigint,
            prefix: "public"
          ),
          null: false
    end

    create index(:tool_instances, [:owner_id], name: "tool_instances_owner_id_index")

    create table(:chat_message_contents, primary_key: false) do
      add :id, :bigserial, null: false, primary_key: true
      add :external_id, :uuid, null: false, default: fragment("gen_random_uuid()")
      add :sequence, :bigint, null: false
      add :kind, :text, null: false
      add :content_text, :text, null: false, default: ""
      add :content_json, :map

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :owner_id,
          references(:users,
            column: :id,
            name: "chat_message_contents_owner_id_fkey",
            type: :bigint,
            prefix: "public"
          ),
          null: false

      add :chat_message_item_id,
          references(:chat_message_items,
            column: :id,
            name: "chat_message_contents_chat_message_item_id_fkey",
            type: :bigint,
            prefix: "public"
          ),
          null: false

      add :file_id,
          references(:files,
            column: :id,
            name: "chat_message_contents_file_id_fkey",
            type: :bigint,
            prefix: "public"
          )
    end

    create index(:chat_message_contents, [:file_id], name: "chat_message_contents_file_id_index")

    create unique_index(:chat_message_contents, [:external_id],
             name: "chat_message_contents_unique_external_id_index"
           )

    create unique_index(:chat_message_contents, [:chat_message_item_id, :sequence],
             name: "chat_message_contents_unique_item_sequence_index"
           )

    create table(:llm_configuration_tag_bindings, primary_key: false) do
      add :id, :bigserial, null: false, primary_key: true

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :owner_id,
          references(:users,
            column: :id,
            name: "llm_configuration_tag_bindings_owner_id_fkey",
            type: :bigint,
            prefix: "public"
          ),
          null: false

      add :llm_configuration_id,
          references(:llm_configurations,
            column: :id,
            name: "llm_configuration_tag_bindings_llm_configuration_id_fkey",
            type: :bigint,
            prefix: "public"
          ),
          null: false

      add :llm_configuration_tag_id,
          references(:llm_configuration_tags,
            column: :id,
            name: "llm_configuration_tag_bindings_llm_configuration_tag_id_fkey",
            type: :bigint,
            prefix: "public"
          ),
          null: false
    end

    create index(:llm_configuration_tag_bindings, [:llm_configuration_tag_id],
             name: "llm_configuration_tag_bindings_llm_configuration_tag_id_index"
           )

    create index(:llm_configuration_tag_bindings, [:llm_configuration_id],
             name: "llm_configuration_tag_bindings_llm_configuration_id_index"
           )

    create index(:llm_configuration_tag_bindings, [:owner_id],
             name: "llm_configuration_tag_bindings_owner_id_index"
           )

    create unique_index(
             :llm_configuration_tag_bindings,
             [:llm_configuration_id, :llm_configuration_tag_id],
             name: "llm_configuration_tag_bindings_unique_pair_index"
           )

    create table(:chat_knowledge_blocks, primary_key: false) do
      add :id, :bigserial, null: false, primary_key: true
      add :enabled, :boolean, null: false, default: true
      add :sequence, :bigint, null: false, default: 0

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :owner_id,
          references(:users,
            column: :id,
            name: "chat_knowledge_blocks_owner_id_fkey",
            type: :bigint,
            prefix: "public"
          ),
          null: false

      add :chat_id,
          references(:chats,
            column: :id,
            name: "chat_knowledge_blocks_chat_id_fkey",
            type: :bigint,
            prefix: "public"
          ),
          null: false

      add :knowledge_block_id, :bigint, null: false
    end

    create index(:chat_knowledge_blocks, [:chat_id, :enabled],
             name: "chat_knowledge_blocks_chat_enabled_index"
           )

    create unique_index(:chat_knowledge_blocks, [:chat_id, :knowledge_block_id],
             name: "chat_knowledge_blocks_unique_pair_index"
           )

    create table(:chat_shares, primary_key: false) do
      add :id, :bigserial, null: false, primary_key: true

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :chat_id,
          references(:chats,
            column: :id,
            name: "chat_shares_chat_id_fkey",
            type: :bigint,
            prefix: "public"
          ),
          null: false

      add :user_group_id,
          references(:user_groups,
            column: :id,
            name: "chat_shares_user_group_id_fkey",
            type: :bigint,
            prefix: "public"
          ),
          null: false

      add :bot_id,
          references(:bots,
            column: :id,
            name: "chat_shares_bot_id_fkey",
            type: :bigint,
            prefix: "public"
          ),
          null: false

      add :llm_configuration_id,
          references(:llm_configurations,
            column: :id,
            name: "chat_shares_llm_configuration_id_fkey",
            type: :bigint,
            prefix: "public"
          ),
          null: false
    end

    create index(:chat_shares, [:llm_configuration_id, :user_group_id],
             name: "chat_shares_config_group_index"
           )

    create index(:chat_shares, [:bot_id, :user_group_id], name: "chat_shares_bot_group_index")

    create index(:chat_shares, [:user_group_id], name: "chat_shares_user_group_id_index")

    create index(:chat_shares, [:chat_id], name: "chat_shares_chat_id_index")

    create unique_index(:chat_shares, [:chat_id, :user_group_id],
             name: "chat_shares_unique_pair_index"
           )

    create table(:bot_shares, primary_key: false) do
      add :id, :bigserial, null: false, primary_key: true

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :bot_id,
          references(:bots,
            column: :id,
            name: "bot_shares_bot_id_fkey",
            type: :bigint,
            prefix: "public"
          ),
          null: false

      add :user_group_id,
          references(:user_groups,
            column: :id,
            name: "bot_shares_user_group_id_fkey",
            type: :bigint,
            prefix: "public"
          ),
          null: false
    end

    create index(:bot_shares, [:user_group_id], name: "bot_shares_user_group_id_index")

    create index(:bot_shares, [:bot_id], name: "bot_shares_bot_id_index")

    create unique_index(:bot_shares, [:bot_id, :user_group_id],
             name: "bot_shares_unique_pair_index"
           )

    create table(:message_bookmarks, primary_key: false) do
      add :id, :bigserial, null: false, primary_key: true

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :owner_id,
          references(:users,
            column: :id,
            name: "message_bookmarks_owner_id_fkey",
            type: :bigint,
            prefix: "public"
          ),
          null: false

      add :chat_message_id, :bigint, null: false
    end

    create index(:message_bookmarks, [:chat_message_id],
             name: "message_bookmarks_chat_message_id_index"
           )

    create index(:message_bookmarks, [:owner_id], name: "message_bookmarks_owner_id_index")

    create unique_index(:message_bookmarks, [:owner_id, :chat_message_id],
             name: "message_bookmarks_unique_owner_chat_message_index"
           )

    create table(:llm_providers, primary_key: false) do
      add :id, :bigserial, null: false, primary_key: true
    end

    alter table(:llm_configurations) do
      modify :provider_id,
             references(:llm_providers,
               column: :id,
               name: "llm_configurations_provider_id_fkey",
               type: :bigint,
               prefix: "public"
             )
    end

    alter table(:llm_providers) do
      add :name, :text, null: false
      add :type, :text, null: false, default: "openrouter_chat_completion"
      add :auth_method, :text, null: false, default: "api_key"
      add :base_url, :text
      add :api_key, :text
      add :oauth_refresh_token, :text

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :owner_id,
          references(:users,
            column: :id,
            name: "llm_providers_owner_id_fkey",
            type: :bigint,
            prefix: "public"
          ),
          null: false
    end

    create table(:knowledge_block_files, primary_key: false) do
      add :id, :bigserial, null: false, primary_key: true
      add :external_id, :uuid, null: false, default: fragment("gen_random_uuid()")
      add :sequence, :bigint, null: false, default: 0
      add :enabled, :boolean, null: false, default: true

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :owner_id,
          references(:users,
            column: :id,
            name: "knowledge_block_files_owner_id_fkey",
            type: :bigint,
            prefix: "public"
          ),
          null: false

      add :knowledge_block_id, :bigint, null: false
      add :file_id, :bigint, null: false
    end

    create index(:knowledge_block_files, [:file_id], name: "knowledge_block_files_file_id_index")

    create index(:knowledge_block_files, [:knowledge_block_id],
             name: "knowledge_block_files_knowledge_block_id_index"
           )

    create unique_index(:knowledge_block_files, [:external_id],
             name: "knowledge_block_files_unique_external_id_index"
           )

    create table(:llm_usage_records, primary_key: false) do
      add :id, :bigserial, null: false, primary_key: true
      add :external_id, :uuid, null: false, default: fragment("gen_random_uuid()")
      add :usage_user_id_snapshot, :bigint, null: false
      add :usage_username_snapshot, :text, null: false
      add :configuration_owner_id_snapshot, :bigint, null: false
      add :llm_configuration_id_snapshot, :bigint, null: false
      add :llm_configuration_external_id_snapshot, :uuid
      add :llm_configuration_label_snapshot, :text, null: false
      add :provider_id_snapshot, :bigint
      add :provider_name_snapshot, :text
      add :provider_type_snapshot, :text
      add :chat_id_snapshot, :bigint, null: false
      add :chat_message_id_snapshot, :bigint, null: false
      add :chat_message_step_id_snapshot, :bigint, null: false
      add :step_sequence, :bigint, null: false
      add :status, :text, null: false, default: "done"
      add :response_final, :boolean, null: false, default: false
      add :occurred_at, :utc_datetime_usec, null: false
      add :input_tokens, :bigint
      add :output_tokens, :bigint
      add :cached_input_tokens, :bigint
      add :reasoning_tokens, :bigint
      add :cost, :float
      add :raw_usage, :map

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :usage_user_id,
          references(:users,
            column: :id,
            name: "llm_usage_records_usage_user_id_fkey",
            type: :bigint,
            prefix: "public"
          )

      add :configuration_owner_id,
          references(:users,
            column: :id,
            name: "llm_usage_records_configuration_owner_id_fkey",
            type: :bigint,
            prefix: "public"
          )

      add :llm_configuration_id,
          references(:llm_configurations,
            column: :id,
            name: "llm_usage_records_llm_configuration_id_fkey",
            type: :bigint,
            prefix: "public"
          )

      add :provider_id,
          references(:llm_providers,
            column: :id,
            name: "llm_usage_records_provider_id_fkey",
            type: :bigint,
            prefix: "public"
          )

      add :chat_id,
          references(:chats,
            column: :id,
            name: "llm_usage_records_chat_id_fkey",
            type: :bigint,
            prefix: "public"
          )

      add :chat_message_id, :bigint
      add :chat_message_step_id, :bigint
    end

    create index(:llm_usage_records, [:usage_user_id_snapshot, :occurred_at],
             name: "llm_usage_records_user_occurred_at_index"
           )

    create index(
             :llm_usage_records,
             [
               :configuration_owner_id_snapshot,
               :llm_configuration_external_id_snapshot,
               :occurred_at
             ],
             name: "llm_usage_records_owner_config_occurred_at_index"
           )

    create index(:llm_usage_records, [:configuration_owner_id_snapshot, :occurred_at],
             name: "llm_usage_records_owner_occurred_at_index"
           )

    create unique_index(:llm_usage_records, [:external_id],
             name: "llm_usage_records_unique_external_id_index"
           )

    create unique_index(:llm_usage_records, [:chat_message_step_id_snapshot],
             name: "llm_usage_records_unique_step_snapshot_index"
           )

    create table(:knowledge_blocks, primary_key: false) do
      add :id, :bigserial, null: false, primary_key: true
    end

    alter table(:llm_configuration_knowledge_blocks) do
      modify :knowledge_block_id,
             references(:knowledge_blocks,
               column: :id,
               name: "llm_configuration_knowledge_blocks_knowledge_block_id_fkey",
               type: :bigint,
               prefix: "public"
             )
    end

    alter table(:user_knowledge_blocks) do
      modify :knowledge_block_id,
             references(:knowledge_blocks,
               column: :id,
               name: "user_knowledge_blocks_knowledge_block_id_fkey",
               type: :bigint,
               prefix: "public"
             )
    end

    alter table(:bots) do
      modify :handoff_message_block_id,
             references(:knowledge_blocks,
               column: :id,
               name: "bots_handoff_message_block_id_fkey",
               type: :bigint,
               prefix: "public"
             )
    end

    alter table(:bot_knowledge_blocks) do
      modify :knowledge_block_id,
             references(:knowledge_blocks,
               column: :id,
               name: "bot_knowledge_blocks_knowledge_block_id_fkey",
               type: :bigint,
               prefix: "public"
             )
    end

    alter table(:knowledge_block_tags) do
      modify :knowledge_block_id,
             references(:knowledge_blocks,
               column: :id,
               name: "knowledge_block_tags_knowledge_block_id_fkey",
               type: :bigint,
               prefix: "public"
             )

      modify :knowledge_tag_id,
             references(:knowledge_tags,
               column: :id,
               name: "knowledge_block_tags_knowledge_tag_id_fkey",
               type: :bigint,
               prefix: "public"
             )
    end

    alter table(:chat_knowledge_blocks) do
      modify :knowledge_block_id,
             references(:knowledge_blocks,
               column: :id,
               name: "chat_knowledge_blocks_knowledge_block_id_fkey",
               type: :bigint,
               prefix: "public"
             )
    end

    alter table(:knowledge_block_files) do
      modify :knowledge_block_id,
             references(:knowledge_blocks,
               column: :id,
               name: "knowledge_block_files_knowledge_block_id_fkey",
               type: :bigint,
               prefix: "public"
             )

      modify :file_id,
             references(:files,
               column: :id,
               name: "knowledge_block_files_file_id_fkey",
               type: :bigint,
               prefix: "public"
             )
    end

    alter table(:knowledge_blocks) do
      add :external_id, :uuid, null: false, default: fragment("gen_random_uuid()")
      add :name, :text, null: false
      add :version, :text, default: ""
      add :content, :text, null: false, default: ""
      add :token_count, :bigint, null: false, default: 0

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :owner_id,
          references(:users,
            column: :id,
            name: "knowledge_blocks_owner_id_fkey",
            type: :bigint,
            prefix: "public"
          ),
          null: false

      add :image_file_id,
          references(:files,
            column: :id,
            name: "knowledge_blocks_image_file_id_fkey",
            type: :bigint,
            prefix: "public"
          )
    end

    create index(:knowledge_blocks, [:image_file_id],
             name: "knowledge_blocks_image_file_id_index"
           )

    create unique_index(:knowledge_blocks, [:owner_id, :external_id],
             name: "knowledge_blocks_unique_owner_external_id_index"
           )

    create table(:web_push_settings, primary_key: false) do
      add :id, :bigserial, null: false, primary_key: true
      add :singleton_key, :text, null: false, default: "default"
      add :enabled, :boolean, null: false, default: false
      add :public_origin, :text
      add :vapid_subject, :text
      add :vapid_public_key, :text, null: false
      add :vapid_private_key, :text, null: false
      add :key_revision, :bigint, null: false, default: 1

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:web_push_settings, [:singleton_key],
             name: "web_push_settings_unique_singleton_key_index"
           )

    create table(:chat_messages, primary_key: false) do
      add :id, :bigserial, null: false, primary_key: true
    end

    alter table(:chat_message_steps) do
      modify :chat_message_id,
             references(:chat_messages,
               column: :id,
               name: "chat_message_steps_chat_message_id_fkey",
               type: :bigint,
               prefix: "public"
             )
    end

    alter table(:chats) do
      modify :last_message_id,
             references(:chat_messages,
               column: :id,
               name: "chats_last_message_id_fkey",
               type: :bigint,
               prefix: "public"
             )

      modify :parent_chat_id,
             references(:chats,
               column: :id,
               name: "chats_parent_chat_id_fkey",
               type: :bigint,
               prefix: "public"
             )

      modify :parent_message_id,
             references(:chat_messages,
               column: :id,
               name: "chats_parent_message_id_fkey",
               type: :bigint,
               prefix: "public"
             )
    end

    alter table(:web_push_generation_events) do
      modify :chat_message_id,
             references(:chat_messages,
               column: :id,
               name: "web_push_generation_events_chat_message_id_fkey",
               type: :bigint,
               prefix: "public"
             )
    end

    alter table(:message_bookmarks) do
      modify :chat_message_id,
             references(:chat_messages,
               column: :id,
               name: "message_bookmarks_chat_message_id_fkey",
               type: :bigint,
               prefix: "public"
             )
    end

    alter table(:llm_usage_records) do
      modify :chat_message_id,
             references(:chat_messages,
               column: :id,
               name: "llm_usage_records_chat_message_id_fkey",
               type: :bigint,
               prefix: "public"
             )

      modify :chat_message_step_id,
             references(:chat_message_steps,
               column: :id,
               name: "llm_usage_records_chat_message_step_id_fkey",
               type: :bigint,
               prefix: "public"
             )
    end

    alter table(:chat_messages) do
      add :role, :text, null: false
      add :status, :text, null: false, default: "done"
      add :error_detail, :text
      add :token_count, :bigint, null: false, default: 0
      add :finished_at, :utc_datetime_usec

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :owner_id,
          references(:users,
            column: :id,
            name: "chat_messages_owner_id_fkey",
            type: :bigint,
            prefix: "public"
          ),
          null: false

      add :chat_id,
          references(:chats,
            column: :id,
            name: "chat_messages_chat_id_fkey",
            type: :bigint,
            prefix: "public"
          ),
          null: false

      add :parent_id,
          references(:chat_messages,
            column: :id,
            name: "chat_messages_parent_id_fkey",
            type: :bigint,
            prefix: "public"
          )

      add :llm_configuration_id,
          references(:llm_configurations,
            column: :id,
            name: "chat_messages_llm_configuration_id_fkey",
            type: :bigint,
            prefix: "public"
          )
    end

    create index(:chat_messages, [:owner_id, :chat_id], name: "chat_messages_owner_chat_id_index")

    create index(:chat_messages, [:chat_id, :parent_id],
             name: "chat_messages_chat_parent_id_index"
           )

    create index(:chat_messages, [:chat_id, :created_at, :id],
             name: "chat_messages_chat_created_id_index"
           )

    create table(:tool_functions, primary_key: false) do
      add :id, :bigserial, null: false, primary_key: true
      add :name, :text, null: false
      add :description, :text, null: false, default: ""
      add :parameters_schema, :map, null: false, default: %{}
      add :enabled, :boolean, null: false, default: true

      add :discovered_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :owner_id,
          references(:users,
            column: :id,
            name: "tool_functions_owner_id_fkey",
            type: :bigint,
            prefix: "public"
          ),
          null: false

      add :tool_instance_id,
          references(:tool_instances,
            column: :id,
            name: "tool_functions_tool_instance_id_fkey",
            type: :bigint,
            prefix: "public"
          ),
          null: false
    end

    create index(:tool_functions, [:owner_id], name: "tool_functions_owner_id_index")

    create unique_index(:tool_functions, [:tool_instance_id, :name],
             name: "tool_functions_unique_instance_name_index"
           )

    create table(:llm_configuration_shares, primary_key: false) do
      add :id, :bigserial, null: false, primary_key: true

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :llm_configuration_id,
          references(:llm_configurations,
            column: :id,
            name: "llm_configuration_shares_llm_configuration_id_fkey",
            type: :bigint,
            prefix: "public"
          ),
          null: false

      add :user_group_id,
          references(:user_groups,
            column: :id,
            name: "llm_configuration_shares_user_group_id_fkey",
            type: :bigint,
            prefix: "public"
          ),
          null: false
    end

    create index(:llm_configuration_shares, [:user_group_id],
             name: "llm_configuration_shares_user_group_id_index"
           )

    create index(:llm_configuration_shares, [:llm_configuration_id],
             name: "llm_configuration_shares_llm_configuration_id_index"
           )

    create unique_index(:llm_configuration_shares, [:llm_configuration_id, :user_group_id],
             name: "llm_configuration_shares_unique_pair_index"
           )

    execute("""
    CREATE INDEX IF NOT EXISTS chat_message_contents_content_text_trgm_index ON chat_message_contents USING gin (content_text gin_trgm_ops) WHERE kind = 'text'
    """)

    execute("""
    CREATE INDEX IF NOT EXISTS bots_name_trgm_index ON bots USING gin (name gin_trgm_ops)
    """)

    execute("""
    CREATE INDEX IF NOT EXISTS chats_note_trgm_index ON chats USING gin (note gin_trgm_ops) WHERE note <> ''
    """)
  end

  def down do
    execute("""
    DROP INDEX IF EXISTS chats_note_trgm_index
    """)

    execute("""
    DROP INDEX IF EXISTS bots_name_trgm_index
    """)

    execute("""
    DROP INDEX IF EXISTS chat_message_contents_content_text_trgm_index
    """)

    drop constraint(
           :llm_configuration_shares,
           "llm_configuration_shares_llm_configuration_id_fkey"
         )

    drop constraint(:llm_configuration_shares, "llm_configuration_shares_user_group_id_fkey")

    drop_if_exists unique_index(
                     :llm_configuration_shares,
                     [:llm_configuration_id, :user_group_id],
                     name: "llm_configuration_shares_unique_pair_index"
                   )

    drop_if_exists index(:llm_configuration_shares, [:llm_configuration_id],
                     name: "llm_configuration_shares_llm_configuration_id_index"
                   )

    drop_if_exists index(:llm_configuration_shares, [:user_group_id],
                     name: "llm_configuration_shares_user_group_id_index"
                   )

    drop table(:llm_configuration_shares)

    drop constraint(:tool_functions, "tool_functions_owner_id_fkey")

    drop constraint(:tool_functions, "tool_functions_tool_instance_id_fkey")

    drop_if_exists unique_index(:tool_functions, [:tool_instance_id, :name],
                     name: "tool_functions_unique_instance_name_index"
                   )

    drop_if_exists index(:tool_functions, [:owner_id], name: "tool_functions_owner_id_index")

    drop table(:tool_functions)

    drop constraint(:chat_messages, "chat_messages_owner_id_fkey")

    drop constraint(:chat_messages, "chat_messages_chat_id_fkey")

    drop constraint(:chat_messages, "chat_messages_parent_id_fkey")

    drop constraint(:chat_messages, "chat_messages_llm_configuration_id_fkey")

    drop_if_exists index(:chat_messages, [:chat_id, :created_at, :id],
                     name: "chat_messages_chat_created_id_index"
                   )

    drop_if_exists index(:chat_messages, [:chat_id, :parent_id],
                     name: "chat_messages_chat_parent_id_index"
                   )

    drop_if_exists index(:chat_messages, [:owner_id, :chat_id],
                     name: "chat_messages_owner_chat_id_index"
                   )

    alter table(:chat_messages) do
      remove :llm_configuration_id
      remove :parent_id
      remove :chat_id
      remove :owner_id
      remove :updated_at
      remove :created_at
      remove :finished_at
      remove :token_count
      remove :error_detail
      remove :status
      remove :role
    end

    drop constraint(:llm_usage_records, "llm_usage_records_chat_message_id_fkey")

    drop constraint(:llm_usage_records, "llm_usage_records_chat_message_step_id_fkey")

    alter table(:llm_usage_records) do
      modify :chat_message_step_id, :bigint
      modify :chat_message_id, :bigint
    end

    drop constraint(:message_bookmarks, "message_bookmarks_chat_message_id_fkey")

    alter table(:message_bookmarks) do
      modify :chat_message_id, :bigint
    end

    drop constraint(
           :web_push_generation_events,
           "web_push_generation_events_chat_message_id_fkey"
         )

    alter table(:web_push_generation_events) do
      modify :chat_message_id, :bigint
    end

    drop constraint(:chats, "chats_last_message_id_fkey")

    drop constraint(:chats, "chats_parent_chat_id_fkey")

    drop constraint(:chats, "chats_parent_message_id_fkey")

    alter table(:chats) do
      modify :parent_message_id, :bigint
      modify :parent_chat_id, :bigint
      modify :last_message_id, :bigint
    end

    drop constraint(:chat_message_steps, "chat_message_steps_chat_message_id_fkey")

    alter table(:chat_message_steps) do
      modify :chat_message_id, :bigint
    end

    drop table(:chat_messages)

    drop_if_exists unique_index(:web_push_settings, [:singleton_key],
                     name: "web_push_settings_unique_singleton_key_index"
                   )

    drop table(:web_push_settings)

    drop constraint(:knowledge_blocks, "knowledge_blocks_owner_id_fkey")

    drop constraint(:knowledge_blocks, "knowledge_blocks_image_file_id_fkey")

    drop_if_exists unique_index(:knowledge_blocks, [:owner_id, :external_id],
                     name: "knowledge_blocks_unique_owner_external_id_index"
                   )

    drop_if_exists index(:knowledge_blocks, [:image_file_id],
                     name: "knowledge_blocks_image_file_id_index"
                   )

    alter table(:knowledge_blocks) do
      remove :image_file_id
      remove :owner_id
      remove :updated_at
      remove :created_at
      remove :token_count
      remove :content
      remove :version
      remove :name
      remove :external_id
    end

    drop constraint(:knowledge_block_files, "knowledge_block_files_knowledge_block_id_fkey")

    drop constraint(:knowledge_block_files, "knowledge_block_files_file_id_fkey")

    alter table(:knowledge_block_files) do
      modify :file_id, :bigint
      modify :knowledge_block_id, :bigint
    end

    drop constraint(:chat_knowledge_blocks, "chat_knowledge_blocks_knowledge_block_id_fkey")

    alter table(:chat_knowledge_blocks) do
      modify :knowledge_block_id, :bigint
    end

    drop constraint(:knowledge_block_tags, "knowledge_block_tags_knowledge_block_id_fkey")

    drop constraint(:knowledge_block_tags, "knowledge_block_tags_knowledge_tag_id_fkey")

    alter table(:knowledge_block_tags) do
      modify :knowledge_tag_id, :bigint
      modify :knowledge_block_id, :bigint
    end

    drop constraint(:bot_knowledge_blocks, "bot_knowledge_blocks_knowledge_block_id_fkey")

    alter table(:bot_knowledge_blocks) do
      modify :knowledge_block_id, :bigint
    end

    drop constraint(:bots, "bots_handoff_message_block_id_fkey")

    alter table(:bots) do
      modify :handoff_message_block_id, :bigint
    end

    drop constraint(:user_knowledge_blocks, "user_knowledge_blocks_knowledge_block_id_fkey")

    alter table(:user_knowledge_blocks) do
      modify :knowledge_block_id, :bigint
    end

    drop constraint(
           :llm_configuration_knowledge_blocks,
           "llm_configuration_knowledge_blocks_knowledge_block_id_fkey"
         )

    alter table(:llm_configuration_knowledge_blocks) do
      modify :knowledge_block_id, :bigint
    end

    drop table(:knowledge_blocks)

    drop constraint(:llm_usage_records, "llm_usage_records_usage_user_id_fkey")

    drop constraint(:llm_usage_records, "llm_usage_records_configuration_owner_id_fkey")

    drop constraint(:llm_usage_records, "llm_usage_records_llm_configuration_id_fkey")

    drop constraint(:llm_usage_records, "llm_usage_records_provider_id_fkey")

    drop constraint(:llm_usage_records, "llm_usage_records_chat_id_fkey")

    drop_if_exists unique_index(:llm_usage_records, [:chat_message_step_id_snapshot],
                     name: "llm_usage_records_unique_step_snapshot_index"
                   )

    drop_if_exists unique_index(:llm_usage_records, [:external_id],
                     name: "llm_usage_records_unique_external_id_index"
                   )

    drop_if_exists index(:llm_usage_records, [:configuration_owner_id_snapshot, :occurred_at],
                     name: "llm_usage_records_owner_occurred_at_index"
                   )

    drop_if_exists index(
                     :llm_usage_records,
                     [
                       :configuration_owner_id_snapshot,
                       :llm_configuration_external_id_snapshot,
                       :occurred_at
                     ],
                     name: "llm_usage_records_owner_config_occurred_at_index"
                   )

    drop_if_exists index(:llm_usage_records, [:usage_user_id_snapshot, :occurred_at],
                     name: "llm_usage_records_user_occurred_at_index"
                   )

    drop table(:llm_usage_records)

    drop constraint(:knowledge_block_files, "knowledge_block_files_owner_id_fkey")

    drop_if_exists unique_index(:knowledge_block_files, [:external_id],
                     name: "knowledge_block_files_unique_external_id_index"
                   )

    drop_if_exists index(:knowledge_block_files, [:knowledge_block_id],
                     name: "knowledge_block_files_knowledge_block_id_index"
                   )

    drop_if_exists index(:knowledge_block_files, [:file_id],
                     name: "knowledge_block_files_file_id_index"
                   )

    drop table(:knowledge_block_files)

    drop constraint(:llm_providers, "llm_providers_owner_id_fkey")

    alter table(:llm_providers) do
      remove :owner_id
      remove :updated_at
      remove :created_at
      remove :oauth_refresh_token
      remove :api_key
      remove :base_url
      remove :auth_method
      remove :type
      remove :name
    end

    drop constraint(:llm_configurations, "llm_configurations_provider_id_fkey")

    alter table(:llm_configurations) do
      modify :provider_id, :bigint
    end

    drop table(:llm_providers)

    drop constraint(:message_bookmarks, "message_bookmarks_owner_id_fkey")

    drop_if_exists unique_index(:message_bookmarks, [:owner_id, :chat_message_id],
                     name: "message_bookmarks_unique_owner_chat_message_index"
                   )

    drop_if_exists index(:message_bookmarks, [:owner_id],
                     name: "message_bookmarks_owner_id_index"
                   )

    drop_if_exists index(:message_bookmarks, [:chat_message_id],
                     name: "message_bookmarks_chat_message_id_index"
                   )

    drop table(:message_bookmarks)

    drop constraint(:bot_shares, "bot_shares_bot_id_fkey")

    drop constraint(:bot_shares, "bot_shares_user_group_id_fkey")

    drop_if_exists unique_index(:bot_shares, [:bot_id, :user_group_id],
                     name: "bot_shares_unique_pair_index"
                   )

    drop_if_exists index(:bot_shares, [:bot_id], name: "bot_shares_bot_id_index")

    drop_if_exists index(:bot_shares, [:user_group_id], name: "bot_shares_user_group_id_index")

    drop table(:bot_shares)

    drop constraint(:chat_shares, "chat_shares_chat_id_fkey")

    drop constraint(:chat_shares, "chat_shares_user_group_id_fkey")

    drop constraint(:chat_shares, "chat_shares_bot_id_fkey")

    drop constraint(:chat_shares, "chat_shares_llm_configuration_id_fkey")

    drop_if_exists unique_index(:chat_shares, [:chat_id, :user_group_id],
                     name: "chat_shares_unique_pair_index"
                   )

    drop_if_exists index(:chat_shares, [:chat_id], name: "chat_shares_chat_id_index")

    drop_if_exists index(:chat_shares, [:user_group_id], name: "chat_shares_user_group_id_index")

    drop_if_exists index(:chat_shares, [:bot_id, :user_group_id],
                     name: "chat_shares_bot_group_index"
                   )

    drop_if_exists index(:chat_shares, [:llm_configuration_id, :user_group_id],
                     name: "chat_shares_config_group_index"
                   )

    drop table(:chat_shares)

    drop constraint(:chat_knowledge_blocks, "chat_knowledge_blocks_owner_id_fkey")

    drop constraint(:chat_knowledge_blocks, "chat_knowledge_blocks_chat_id_fkey")

    drop_if_exists unique_index(:chat_knowledge_blocks, [:chat_id, :knowledge_block_id],
                     name: "chat_knowledge_blocks_unique_pair_index"
                   )

    drop_if_exists index(:chat_knowledge_blocks, [:chat_id, :enabled],
                     name: "chat_knowledge_blocks_chat_enabled_index"
                   )

    drop table(:chat_knowledge_blocks)

    drop constraint(
           :llm_configuration_tag_bindings,
           "llm_configuration_tag_bindings_owner_id_fkey"
         )

    drop constraint(
           :llm_configuration_tag_bindings,
           "llm_configuration_tag_bindings_llm_configuration_id_fkey"
         )

    drop constraint(
           :llm_configuration_tag_bindings,
           "llm_configuration_tag_bindings_llm_configuration_tag_id_fkey"
         )

    drop_if_exists unique_index(
                     :llm_configuration_tag_bindings,
                     [:llm_configuration_id, :llm_configuration_tag_id],
                     name: "llm_configuration_tag_bindings_unique_pair_index"
                   )

    drop_if_exists index(:llm_configuration_tag_bindings, [:owner_id],
                     name: "llm_configuration_tag_bindings_owner_id_index"
                   )

    drop_if_exists index(:llm_configuration_tag_bindings, [:llm_configuration_id],
                     name: "llm_configuration_tag_bindings_llm_configuration_id_index"
                   )

    drop_if_exists index(:llm_configuration_tag_bindings, [:llm_configuration_tag_id],
                     name: "llm_configuration_tag_bindings_llm_configuration_tag_id_index"
                   )

    drop table(:llm_configuration_tag_bindings)

    drop constraint(:chat_message_contents, "chat_message_contents_owner_id_fkey")

    drop constraint(:chat_message_contents, "chat_message_contents_chat_message_item_id_fkey")

    drop constraint(:chat_message_contents, "chat_message_contents_file_id_fkey")

    drop_if_exists unique_index(:chat_message_contents, [:chat_message_item_id, :sequence],
                     name: "chat_message_contents_unique_item_sequence_index"
                   )

    drop_if_exists unique_index(:chat_message_contents, [:external_id],
                     name: "chat_message_contents_unique_external_id_index"
                   )

    drop_if_exists index(:chat_message_contents, [:file_id],
                     name: "chat_message_contents_file_id_index"
                   )

    drop table(:chat_message_contents)

    drop constraint(:tool_instances, "tool_instances_owner_id_fkey")

    drop_if_exists index(:tool_instances, [:owner_id], name: "tool_instances_owner_id_index")

    alter table(:tool_instances) do
      remove :owner_id
      remove :updated_at
      remove :created_at
      remove :last_discovery_error
      remove :last_discovered_at
      remove :rps_limit
      remove :max_output_tokens
      remove :secrets
      remove :config
      remove :alias
      remove :description
      remove :name
      remove :type
    end

    drop constraint(:bot_user_tool_bindings, "bot_user_tool_bindings_tool_instance_id_fkey")

    alter table(:bot_user_tool_bindings) do
      modify :tool_instance_id, :bigint
    end

    drop constraint(:chat_tool_bindings, "chat_tool_bindings_tool_instance_id_fkey")

    alter table(:chat_tool_bindings) do
      modify :tool_instance_id, :bigint
    end

    drop constraint(:bot_tool_bindings, "bot_tool_bindings_tool_instance_id_fkey")

    alter table(:bot_tool_bindings) do
      modify :tool_instance_id, :bigint
    end

    drop constraint(:outlet_pairing_requests, "outlet_pairing_requests_tool_instance_id_fkey")

    alter table(:outlet_pairing_requests) do
      modify :tool_instance_id, :bigint
    end

    drop table(:tool_instances)

    drop_if_exists unique_index(:users, [:username], name: "users_unique_username_index")

    alter table(:users) do
      remove :updated_at
      remove :created_at
      remove :preferred_theme
      remove :preferred_locale
      remove :is_admin
      remove :hashed_password
      remove :username
    end

    drop constraint(:knowledge_tags, "knowledge_tags_owner_id_fkey")

    drop constraint(:knowledge_tags, "knowledge_tags_parent_id_fkey")

    alter table(:knowledge_tags) do
      modify :parent_id, :bigint
      modify :owner_id, :bigint
    end

    drop constraint(:knowledge_block_tags, "knowledge_block_tags_owner_id_fkey")

    alter table(:knowledge_block_tags) do
      modify :owner_id, :bigint
    end

    drop constraint(:web_push_generation_events, "web_push_generation_events_owner_id_fkey")

    alter table(:web_push_generation_events) do
      modify :owner_id, :bigint
    end

    drop constraint(:web_push_subscriptions, "web_push_subscriptions_owner_id_fkey")

    alter table(:web_push_subscriptions) do
      modify :owner_id, :bigint
    end

    drop constraint(:llm_configurations, "llm_configurations_owner_id_fkey")

    alter table(:llm_configurations) do
      modify :owner_id, :bigint
    end

    drop constraint(:bot_knowledge_blocks, "bot_knowledge_blocks_owner_id_fkey")

    drop constraint(:bot_knowledge_blocks, "bot_knowledge_blocks_bot_id_fkey")

    alter table(:bot_knowledge_blocks) do
      modify :bot_id, :bigint
      modify :owner_id, :bigint
    end

    drop constraint(:bots, "bots_owner_id_fkey")

    drop constraint(:bots, "bots_image_file_id_fkey")

    drop constraint(:bots, "bots_default_llm_configuration_id_fkey")

    alter table(:bots) do
      modify :default_llm_configuration_id, :bigint
      modify :image_file_id, :bigint
      modify :owner_id, :bigint
    end

    drop constraint(:bot_user_tool_bindings, "bot_user_tool_bindings_owner_id_fkey")

    drop constraint(:bot_user_tool_bindings, "bot_user_tool_bindings_bot_id_fkey")

    alter table(:bot_user_tool_bindings) do
      modify :bot_id, :bigint
      modify :owner_id, :bigint
    end

    drop constraint(:chat_tool_bindings, "chat_tool_bindings_owner_id_fkey")

    drop constraint(:chat_tool_bindings, "chat_tool_bindings_chat_id_fkey")

    alter table(:chat_tool_bindings) do
      modify :chat_id, :bigint
      modify :owner_id, :bigint
    end

    drop constraint(:bot_tool_bindings, "bot_tool_bindings_owner_id_fkey")

    drop constraint(:bot_tool_bindings, "bot_tool_bindings_bot_id_fkey")

    alter table(:bot_tool_bindings) do
      modify :bot_id, :bigint
      modify :owner_id, :bigint
    end

    drop constraint(:user_knowledge_blocks, "user_knowledge_blocks_owner_id_fkey")

    alter table(:user_knowledge_blocks) do
      modify :owner_id, :bigint
    end

    drop constraint(:chats, "chats_owner_id_fkey")

    drop constraint(:chats, "chats_bot_id_fkey")

    drop constraint(:chats, "chats_llm_configuration_id_fkey")

    alter table(:chats) do
      modify :llm_configuration_id, :bigint
      modify :bot_id, :bigint
      modify :owner_id, :bigint
    end

    drop constraint(:outlet_pairing_requests, "outlet_pairing_requests_approved_by_id_fkey")

    alter table(:outlet_pairing_requests) do
      modify :approved_by_id, :bigint
    end

    drop constraint(:chat_message_items, "chat_message_items_owner_id_fkey")

    drop constraint(:chat_message_items, "chat_message_items_chat_message_step_id_fkey")

    drop constraint(:chat_message_items, "chat_message_items_tool_call_item_id_fkey")

    alter table(:chat_message_items) do
      modify :tool_call_item_id, :bigint
      modify :chat_message_step_id, :bigint
      modify :owner_id, :bigint
    end

    drop constraint(:chat_upload_sessions, "chat_upload_sessions_owner_id_fkey")

    drop constraint(:chat_upload_sessions, "chat_upload_sessions_chat_id_fkey")

    alter table(:chat_upload_sessions) do
      modify :chat_id, :bigint
      modify :owner_id, :bigint
    end

    drop constraint(
           :bot_compatible_configuration_tags,
           "bot_compatible_configuration_tags_owner_id_fkey"
         )

    drop constraint(
           :bot_compatible_configuration_tags,
           "bot_compatible_configuration_tags_bot_id_fkey"
         )

    drop constraint(
           :bot_compatible_configuration_tags,
           "bot_compatible_configuration_tags_llm_configuration_tag_id_fkey"
         )

    alter table(:bot_compatible_configuration_tags) do
      modify :llm_configuration_tag_id, :bigint
      modify :bot_id, :bigint
      modify :owner_id, :bigint
    end

    drop constraint(:llm_configuration_tags, "llm_configuration_tags_owner_id_fkey")

    alter table(:llm_configuration_tags) do
      modify :owner_id, :bigint
    end

    drop constraint(
           :llm_configuration_knowledge_blocks,
           "llm_configuration_knowledge_blocks_owner_id_fkey"
         )

    drop constraint(
           :llm_configuration_knowledge_blocks,
           "llm_configuration_knowledge_blocks_llm_configuration_id_fkey"
         )

    alter table(:llm_configuration_knowledge_blocks) do
      modify :llm_configuration_id, :bigint
      modify :owner_id, :bigint
    end

    drop constraint(:chat_message_steps, "chat_message_steps_owner_id_fkey")

    alter table(:chat_message_steps) do
      modify :owner_id, :bigint
    end

    drop constraint(:user_group_memberships, "user_group_memberships_user_id_fkey")

    drop constraint(:user_group_memberships, "user_group_memberships_user_group_id_fkey")

    alter table(:user_group_memberships) do
      modify :user_group_id, :bigint
      modify :user_id, :bigint
    end

    drop table(:users)

    drop_if_exists unique_index(:knowledge_tags, [:owner_id, :full_name],
                     name: "knowledge_tags_unique_full_name_index"
                   )

    drop table(:knowledge_tags)

    drop_if_exists unique_index(:knowledge_block_tags, [:knowledge_block_id, :knowledge_tag_id],
                     name: "knowledge_block_tags_unique_pair_index"
                   )

    drop table(:knowledge_block_tags)

    drop table(:tokens)

    drop_if_exists unique_index(:files, [:external_id], name: "files_unique_external_id_index")

    drop_if_exists index(:files, [:sha256], name: "files_sha256_index")

    drop table(:files)

    drop_if_exists unique_index(:web_push_generation_events, [:chat_message_id, :status],
                     name: "web_push_generation_events_unique_message_status_index"
                   )

    drop_if_exists index(:web_push_generation_events, [:owner_id],
                     name: "web_push_generation_events_owner_id_index"
                   )

    drop table(:web_push_generation_events)

    drop_if_exists unique_index(:web_push_subscriptions, [:endpoint],
                     name: "web_push_subscriptions_unique_endpoint_index"
                   )

    drop_if_exists index(:web_push_subscriptions, [:owner_id],
                     name: "web_push_subscriptions_owner_id_index"
                   )

    drop table(:web_push_subscriptions)

    drop_if_exists unique_index(:llm_configurations, [:external_id],
                     name: "llm_configurations_unique_external_id_index"
                   )

    drop table(:llm_configurations)

    drop_if_exists unique_index(:bot_knowledge_blocks, [:bot_id, :knowledge_block_id],
                     name: "bot_knowledge_blocks_unique_pair_index"
                   )

    drop_if_exists index(:bot_knowledge_blocks, [:bot_id, :enabled],
                     name: "bot_knowledge_blocks_bot_enabled_index"
                   )

    drop table(:bot_knowledge_blocks)

    drop_if_exists unique_index(:bots, [:external_id], name: "bots_unique_external_id_index")

    drop_if_exists index(:bots, [:image_file_id], name: "bots_image_file_id_index")

    drop_if_exists index(:bots, [:default_llm_configuration_id],
                     name: "bots_default_llm_configuration_id_index"
                   )

    drop_if_exists index(:bots, [:handoff_message_block_id],
                     name: "bots_handoff_message_block_id_index"
                   )

    drop table(:bots)

    drop_if_exists unique_index(:bot_user_tool_bindings, [:owner_id, :bot_id, :tool_instance_id],
                     name: "bot_user_tool_bindings_unique_owner_bot_tool_instance_index"
                   )

    drop table(:bot_user_tool_bindings)

    drop_if_exists unique_index(:chat_tool_bindings, [:chat_id, :tool_instance_id],
                     name: "chat_tool_bindings_unique_chat_tool_instance_index"
                   )

    drop_if_exists index(:chat_tool_bindings, [:owner_id],
                     name: "chat_tool_bindings_owner_id_index"
                   )

    drop_if_exists index(:chat_tool_bindings, [:chat_id, :enabled],
                     name: "chat_tool_bindings_chat_enabled_index"
                   )

    drop table(:chat_tool_bindings)

    drop_if_exists unique_index(:bot_tool_bindings, [:bot_id, :tool_instance_id],
                     name: "bot_tool_bindings_unique_bot_tool_instance_index"
                   )

    drop_if_exists index(:bot_tool_bindings, [:owner_id],
                     name: "bot_tool_bindings_owner_id_index"
                   )

    drop table(:bot_tool_bindings)

    drop_if_exists unique_index(:user_knowledge_blocks, [:owner_id, :knowledge_block_id],
                     name: "user_knowledge_blocks_unique_pair_index"
                   )

    drop_if_exists index(:user_knowledge_blocks, [:owner_id],
                     name: "user_knowledge_blocks_owner_id_index"
                   )

    drop_if_exists index(:user_knowledge_blocks, [:owner_id, :enabled],
                     name: "user_knowledge_blocks_owner_enabled_index"
                   )

    drop table(:user_knowledge_blocks)

    drop_if_exists index(:chats, [:owner_id, :updated_at, :id],
                     name: "chats_owner_updated_id_index"
                   )

    drop_if_exists index(:chats, [:parent_chat_id], name: "chats_parent_chat_id_index")

    drop_if_exists index(:chats, [:parent_message_id], name: "chats_parent_message_id_index")

    drop_if_exists index(:chats, [:parent_relation_kind],
                     name: "chats_parent_relation_kind_index"
                   )

    drop table(:chats)

    drop_if_exists unique_index(:outlet_pairing_requests, [:user_code],
                     name: "outlet_pairing_requests_unique_user_code_index"
                   )

    drop_if_exists index(:outlet_pairing_requests, [:device_code_hash],
                     name: "outlet_pairing_requests_device_code_hash_index"
                   )

    drop_if_exists index(:outlet_pairing_requests, [:status, :expires_at, :created_at],
                     name: "outlet_pairing_requests_status_expires_created_index"
                   )

    drop table(:outlet_pairing_requests)

    drop_if_exists unique_index(:chat_message_items, [:chat_message_step_id, :sequence],
                     name: "chat_message_items_unique_step_sequence_index"
                   )

    drop_if_exists index(:chat_message_items, [:tool_call_item_id],
                     name: "chat_message_items_tool_call_item_id_index"
                   )

    drop table(:chat_message_items)

    drop_if_exists unique_index(:chat_upload_sessions, [:external_id],
                     name: "chat_upload_sessions_unique_external_id_index"
                   )

    drop_if_exists index(:chat_upload_sessions, [:chat_id],
                     name: "chat_upload_sessions_chat_id_index"
                   )

    drop_if_exists index(:chat_upload_sessions, [:owner_id],
                     name: "chat_upload_sessions_owner_id_index"
                   )

    drop_if_exists index(:chat_upload_sessions, [:status],
                     name: "chat_upload_sessions_status_index"
                   )

    drop_if_exists index(:chat_upload_sessions, [:expires_at],
                     name: "chat_upload_sessions_expires_at_index"
                   )

    drop table(:chat_upload_sessions)

    drop_if_exists unique_index(:user_groups, [:name], name: "user_groups_unique_name_index")

    drop table(:user_groups)

    drop_if_exists unique_index(
                     :bot_compatible_configuration_tags,
                     [:bot_id, :llm_configuration_tag_id],
                     name: "bot_compatible_configuration_tags_unique_pair_index"
                   )

    drop_if_exists index(:bot_compatible_configuration_tags, [:owner_id],
                     name: "bot_compatible_configuration_tags_owner_id_index"
                   )

    drop_if_exists index(:bot_compatible_configuration_tags, [:bot_id],
                     name: "bot_compatible_configuration_tags_bot_id_index"
                   )

    drop_if_exists index(:bot_compatible_configuration_tags, [:llm_configuration_tag_id],
                     name: "bot_compatible_configuration_tags_llm_configuration_tag_id_index"
                   )

    drop table(:bot_compatible_configuration_tags)

    drop_if_exists unique_index(:llm_configuration_tags, [:owner_id, :name],
                     name: "llm_configuration_tags_unique_name_index"
                   )

    drop table(:llm_configuration_tags)

    drop_if_exists unique_index(
                     :llm_configuration_knowledge_blocks,
                     [:llm_configuration_id, :knowledge_block_id],
                     name: "llm_configuration_knowledge_blocks_unique_pair_index"
                   )

    drop_if_exists index(:llm_configuration_knowledge_blocks, [:llm_configuration_id, :enabled],
                     name: "llm_configuration_knowledge_blocks_config_enabled_index"
                   )

    drop table(:llm_configuration_knowledge_blocks)

    drop_if_exists unique_index(:chat_message_steps, [:chat_message_id, :sequence],
                     name: "chat_message_steps_unique_chat_message_sequence_index"
                   )

    drop table(:chat_message_steps)

    drop_if_exists unique_index(:user_group_memberships, [:user_id, :user_group_id],
                     name: "user_group_memberships_unique_pair_index"
                   )

    drop_if_exists index(:user_group_memberships, [:user_id],
                     name: "user_group_memberships_user_id_index"
                   )

    drop_if_exists index(:user_group_memberships, [:user_group_id],
                     name: "user_group_memberships_user_group_id_index"
                   )

    drop table(:user_group_memberships)
    # Uncomment this if you actually want to uninstall the extensions
    # when this migration is rolled back:
    execute(
      "DROP FUNCTION IF EXISTS uuid_generate_v7(), ash_raise_error(jsonb), ash_raise_error(jsonb, ANYCOMPATIBLE), ash_elixir_and(BOOLEAN, ANYCOMPATIBLE), ash_elixir_and(ANYCOMPATIBLE, ANYCOMPATIBLE), ash_elixir_or(ANYCOMPATIBLE, ANYCOMPATIBLE), ash_elixir_or(BOOLEAN, ANYCOMPATIBLE), ash_trim_whitespace(text[]), ash_required(ANYCOMPATIBLE, jsonb)"
    )

    # execute("DROP EXTENSION IF EXISTS \"pg_trgm\"")
  end
end
