defmodule IntellectualClub.Repo.Migrations.AddManualPricingToLlmConfigurations do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:llm_configurations) do
      add :cold_input_price_per_million_tokens, :float
      add :cached_input_price_per_million_tokens, :float
      add :output_price_per_million_tokens, :float
    end
  end

  def down do
    alter table(:llm_configurations) do
      remove :output_price_per_million_tokens
      remove :cached_input_price_per_million_tokens
      remove :cold_input_price_per_million_tokens
    end
  end
end
