defmodule IntellectualClub.Repo.Migrations.AddBackgroundTaskLifecycleMessage do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:background_tasks) do
      add :lifecycle_message_id,
          references(:chat_messages,
            column: :id,
            name: "background_tasks_lifecycle_message_id_fkey",
            type: :bigint,
            prefix: "public",
            on_delete: :nilify_all
          )
    end

    execute("""
    UPDATE background_tasks
    SET lifecycle_message_id = source_message_id
    WHERE lifecycle_message_id IS NULL AND source_message_id IS NOT NULL
    """)

    create index(:background_tasks, [:lifecycle_message_id, :id],
             name: "background_tasks_active_lifecycle_message_index",
             where: "status IN ('queued', 'running')"
           )
  end

  def down do
    drop constraint(:background_tasks, "background_tasks_lifecycle_message_id_fkey")

    drop_if_exists index(:background_tasks, [:lifecycle_message_id, :id],
                     name: "background_tasks_active_lifecycle_message_index"
                   )

    alter table(:background_tasks) do
      remove :lifecycle_message_id
    end
  end
end
