defmodule IntellectualClub.Repo.Migrations.ManagedSecrets do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:managed_secrets, primary_key: false) do
      add :id, :bigserial, null: false, primary_key: true
      add :external_id, :uuid, null: false, default: fragment("gen_random_uuid()")
      add :name, :text, null: false
      add :description, :text, null: false, default: ""
      add :encrypted_value, :binary, null: false

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :owner_id,
          references(:users,
            column: :id,
            name: "managed_secrets_owner_id_fkey",
            type: :bigint,
            prefix: "public"
          ),
          null: false
    end

    create index(:managed_secrets, [:owner_id], name: "managed_secrets_owner_id_index")

    create unique_index(:managed_secrets, [:owner_id, :external_id],
             name: "managed_secrets_unique_owner_external_id_index"
           )

    create table(:tool_instance_secrets, primary_key: false) do
      add :id, :bigserial, null: false, primary_key: true
      add :external_id, :uuid, null: false, default: fragment("gen_random_uuid()")
      add :env_name, :text, null: false
      add :sequence, :bigint, null: false, default: 0
      add :enabled, :boolean, null: false, default: true

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :owner_id,
          references(:users,
            column: :id,
            name: "tool_instance_secrets_owner_id_fkey",
            type: :bigint,
            prefix: "public"
          ),
          null: false

      add :tool_instance_id,
          references(:tool_instances,
            column: :id,
            name: "tool_instance_secrets_tool_instance_id_fkey",
            type: :bigint,
            prefix: "public"
          ),
          null: false

      add :secret_id,
          references(:managed_secrets,
            column: :id,
            name: "tool_instance_secrets_secret_id_fkey",
            type: :bigint,
            prefix: "public"
          ),
          null: false
    end

    create index(:tool_instance_secrets, [:secret_id],
             name: "tool_instance_secrets_secret_id_index"
           )

    create index(:tool_instance_secrets, [:tool_instance_id],
             name: "tool_instance_secrets_tool_id_index"
           )

    create unique_index(:tool_instance_secrets, [:external_id],
             name: "tool_instance_secrets_unique_external_id_index"
           )

    create unique_index(:tool_instance_secrets, [:tool_instance_id, :env_name],
             name: "tool_instance_secrets_unique_tool_env_name_index"
           )

    create table(:knowledge_block_secrets, primary_key: false) do
      add :id, :bigserial, null: false, primary_key: true
      add :external_id, :uuid, null: false, default: fragment("gen_random_uuid()")
      add :env_name, :text, null: false
      add :sequence, :bigint, null: false, default: 0
      add :enabled, :boolean, null: false, default: true

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :owner_id,
          references(:users,
            column: :id,
            name: "knowledge_block_secrets_owner_id_fkey",
            type: :bigint,
            prefix: "public"
          ),
          null: false

      add :knowledge_block_id,
          references(:knowledge_blocks,
            column: :id,
            name: "knowledge_block_secrets_knowledge_block_id_fkey",
            type: :bigint,
            prefix: "public"
          ),
          null: false

      add :secret_id,
          references(:managed_secrets,
            column: :id,
            name: "knowledge_block_secrets_secret_id_fkey",
            type: :bigint,
            prefix: "public"
          ),
          null: false
    end

    create index(:knowledge_block_secrets, [:secret_id],
             name: "knowledge_block_secrets_secret_id_index"
           )

    create index(:knowledge_block_secrets, [:knowledge_block_id],
             name: "knowledge_block_secrets_block_id_index"
           )

    create unique_index(:knowledge_block_secrets, [:knowledge_block_id, :env_name],
             name: "knowledge_block_secrets_unique_block_env_name_index"
           )

    create unique_index(:knowledge_block_secrets, [:external_id],
             name: "knowledge_block_secrets_unique_external_id_index"
           )
  end

  def down do
    drop constraint(:knowledge_block_secrets, "knowledge_block_secrets_owner_id_fkey")

    drop constraint(:knowledge_block_secrets, "knowledge_block_secrets_knowledge_block_id_fkey")

    drop constraint(:knowledge_block_secrets, "knowledge_block_secrets_secret_id_fkey")

    drop_if_exists unique_index(:knowledge_block_secrets, [:external_id],
                     name: "knowledge_block_secrets_unique_external_id_index"
                   )

    drop_if_exists unique_index(:knowledge_block_secrets, [:knowledge_block_id, :env_name],
                     name: "knowledge_block_secrets_unique_block_env_name_index"
                   )

    drop_if_exists index(:knowledge_block_secrets, [:knowledge_block_id],
                     name: "knowledge_block_secrets_block_id_index"
                   )

    drop_if_exists index(:knowledge_block_secrets, [:secret_id],
                     name: "knowledge_block_secrets_secret_id_index"
                   )

    drop table(:knowledge_block_secrets)

    drop constraint(:tool_instance_secrets, "tool_instance_secrets_owner_id_fkey")

    drop constraint(:tool_instance_secrets, "tool_instance_secrets_tool_instance_id_fkey")

    drop constraint(:tool_instance_secrets, "tool_instance_secrets_secret_id_fkey")

    drop_if_exists unique_index(:tool_instance_secrets, [:tool_instance_id, :env_name],
                     name: "tool_instance_secrets_unique_tool_env_name_index"
                   )

    drop_if_exists unique_index(:tool_instance_secrets, [:external_id],
                     name: "tool_instance_secrets_unique_external_id_index"
                   )

    drop_if_exists index(:tool_instance_secrets, [:tool_instance_id],
                     name: "tool_instance_secrets_tool_id_index"
                   )

    drop_if_exists index(:tool_instance_secrets, [:secret_id],
                     name: "tool_instance_secrets_secret_id_index"
                   )

    drop table(:tool_instance_secrets)

    drop constraint(:managed_secrets, "managed_secrets_owner_id_fkey")

    drop_if_exists unique_index(:managed_secrets, [:owner_id, :external_id],
                     name: "managed_secrets_unique_owner_external_id_index"
                   )

    drop_if_exists index(:managed_secrets, [:owner_id], name: "managed_secrets_owner_id_index")

    drop table(:managed_secrets)
  end
end
