defmodule IntellectualClub.Repo.Migrations.AddWebSearchEnabledToLlmConfigurations do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:llm_configurations) do
      add :web_search_enabled, :boolean, null: false, default: false
    end
  end

  def down do
    alter table(:llm_configurations) do
      remove :web_search_enabled
    end
  end
end
