defmodule IntellectualClub.Repo.Migrations.AddGenerationRecoveryGate do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:chat_messages) do
      add :generation_recovery, :map
    end
  end

  def down do
    alter table(:chat_messages) do
      remove :generation_recovery
    end
  end
end
