defmodule IntellectualClub.Repo.Migrations.CreateChatMessageStepRequestFiles do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:chat_message_step_request_files, primary_key: false) do
      add :id, :bigserial, null: false, primary_key: true
      add :reference_key, :uuid, null: false
      add :source_file_external_id, :uuid, null: false
      add :variant_key, :text, null: false

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :chat_message_step_id,
          references(:chat_message_steps,
            column: :id,
            name: "chat_message_step_request_files_chat_message_step_id_fkey",
            type: :bigint,
            prefix: "public"
          ),
          null: false

      add :file_id,
          references(:files,
            column: :id,
            name: "chat_message_step_request_files_file_id_fkey",
            type: :bigint,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:chat_message_step_request_files, [:file_id],
             name: "chat_message_step_request_files_unique_file_index"
           )

    create unique_index(:chat_message_step_request_files, [:chat_message_step_id, :reference_key],
             name: "chat_message_step_request_files_unique_step_reference_index"
           )
  end

  def down do
    drop constraint(
           :chat_message_step_request_files,
           "chat_message_step_request_files_chat_message_step_id_fkey"
         )

    drop constraint(
           :chat_message_step_request_files,
           "chat_message_step_request_files_file_id_fkey"
         )

    drop_if_exists unique_index(
                     :chat_message_step_request_files,
                     [:chat_message_step_id, :reference_key],
                     name: "chat_message_step_request_files_unique_step_reference_index"
                   )

    drop_if_exists unique_index(:chat_message_step_request_files, [:file_id],
                     name: "chat_message_step_request_files_unique_file_index"
                   )

    drop table(:chat_message_step_request_files)
  end
end
