defmodule IntellectualClub.Repo.Migrations.ClassifyToolInstanceSecrets do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:tool_instance_secrets) do
      add :kind, :text, null: false, default: "environment"
    end

    drop_if_exists unique_index(:tool_instance_secrets, [:tool_instance_id, :env_name],
                     name: "tool_instance_secrets_unique_tool_env_name_index"
                   )

    create unique_index(:tool_instance_secrets, [:tool_instance_id, :kind, :env_name],
             name: "tool_instance_secrets_unique_tool_kind_env_name_index"
           )
  end

  def down do
    raise "This migration is irreversible after driver-secret backfill; " <>
            "restore the pre-upgrade database backup to run an older release."
  end
end
