defmodule IntellectualClub.Repo.Migrations.AddLlmConfigurationStandardParameters do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:llm_configurations) do
      add :temperature, :float
      add :reasoning_effort, :text
    end
  end

  def down do
    alter table(:llm_configurations) do
      remove :reasoning_effort
      remove :temperature
    end
  end
end
