defmodule IntellectualClub.Repo.Migrations.SteeringToolInterruption do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:chat_message_items) do
      add :steering_interruption, :text
    end

    alter table(:chat_queued_messages) do
      add :delivery_mode, :text, null: false, default: "normal"
    end

    alter table(:tool_functions) do
      add :safe_to_interrupt, :boolean, null: false, default: false
    end
  end

  def down do
    alter table(:tool_functions) do
      remove :safe_to_interrupt
    end

    alter table(:chat_queued_messages) do
      remove :delivery_mode
    end

    alter table(:chat_message_items) do
      remove :steering_interruption
    end
  end
end
