export const CODEMIRROR_RU_PHRASES: Record<string, string> = {
  'Control character': 'Управляющий символ',
  'Selection deleted': 'Выделение удалено',
  'Go to line': 'Перейти к строке',
  go: 'Перейти',
  Find: 'Найти',
  Replace: 'Заменить',
  next: 'следующее',
  previous: 'предыдущее',
  all: 'все',
  'match case': 'учитывать регистр',
  'by word': 'слово целиком',
  replace: 'заменить',
  'replace all': 'заменить все',
  close: 'закрыть',
  'current match': 'текущее совпадение',
  'replaced $ matches': 'заменено совпадений: $',
  'replaced match on line $': 'заменено совпадение в строке $',
  'on line': 'в строке',
  'Fold line': 'Свернуть строку',
  'Unfold line': 'Развернуть строку',
};
